"""new tables

Revision ID: 4989bfe33bc9
Revises: 8e95c318dcb8
Create Date: 2025-05-03 21:38:36.402079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4989bfe33bc9'
down_revision: Union[str, None] = '8e95c318dcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_event_id', table_name='events')
    op.drop_index('ix_events_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_players_id', table_name='players')
    op.drop_index('ix_players_player_id', table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jersey_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('from_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draft_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draft_round', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draft_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='players_pkey')
    )
    op.create_index('ix_players_player_id', 'players', ['player_id'], unique=True)
    op.create_index('ix_players_id', 'players', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name='events_league_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=True)
    # ### end Alembic commands ###
