"""cleaned up models

Revision ID: ce3106c9699e
Revises: 80d4df1c33a0
Create Date: 2025-05-12 16:22:46.923185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce3106c9699e'
down_revision: Union[str, None] = '80d4df1c33a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_NBA_player_gaemlogs_id', table_name='NBA_player_gaemlogs')
    op.drop_table('NBA_player_gaemlogs')
    op.add_column('NBA_events', sa.Column('status', sa.String(), nullable=True))
    op.add_column('NBA_player_props', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.alter_column('NBA_players', 'birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'from_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'to_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'draft_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'draft_round',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'draft_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('NBA_team_odds', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NBA_team_odds', 'last_update')
    op.alter_column('NBA_players', 'draft_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'draft_round',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'draft_year',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'to_year',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'from_year',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('NBA_players', 'birth_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('NBA_player_props', 'last_update')
    op.drop_column('NBA_events', 'status')
    op.create_table('NBA_player_gaemlogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_goals_made', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_goal_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('three_pt_made', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('three_pt_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('three_pt_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('free_throw_made', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('free_throw_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('free_throw_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('offensive_rebound', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defensive_rebound', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rebounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turnovers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personal_fouls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plus_minus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['NBA_events.id'], name='NBA_player_gaemlogs_game_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['NBA_players.id'], name='NBA_player_gaemlogs_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='NBA_player_gaemlogs_pkey')
    )
    op.create_index('ix_NBA_player_gaemlogs_id', 'NBA_player_gaemlogs', ['id'], unique=False)
    # ### end Alembic commands ###
